rubycorns/rorganize.it

- app/assets/stylesheets/custom/custom.css.scss
- app/views/groups/_remove_from_group.html.haml
- app/views/groups/show.html.haml
- app/views/layouts/application.html.erb
- app/views/people/show.html.haml
- spec/features/admin_remove_person_spec.rb
this adds links for admins in the group#show and person#show views to remove the person from the group
> Remove person from group, closes #300

- app/assets/stylesheets/custom/_bootstrap_vars.scss
- app/assets/stylesheets/custom/custom.css.scss
- app/controllers/pages_controller.rb
- app/views/pages/index.html.haml
Some counter stuff for the home page and a little of design-ish stuff
> add statistics, closes #286

- app/views/pages/about.html.haml
Please do no merge this, until the 'roar@rorganize.it' email address has been created. The mailto link is pointing at this email address.
Many thanks x
> DO NOT MERGE

- Gemfile
- Gemfile.lock
- app/controllers/groups_controller.rb
- app/helpers/groups_helper.rb
- app/models/group.rb
- app/views/groups/_form.html.haml
- app/views/groups/index.html.haml
- app/views/groups/show.html.haml
- db/migrate/20150217194042_add_city_and_country_to_groups.rb
- db/schema.rb
- db/seeds.rb
- public/403.html
- spec/features/group_edit_spec.rb
Do not merge!
Add form fields.
Migrate existing data or update manually after deploy.
> WIP Adds city and country to groups list.

- README.md
Fixes #323 
Do you want to do the honors @berlintam ? :)
> Fix README badges links

- .travis.yml
- config/initializers/devise.rb
- db/seeds.rb
tiny things, just gonna merge....
> Small things

- .travis.yml
As per @lislis's request, we added this line to the travis.yml file that will cache our bundle, and make our tests run much faster...Correct me if I'm wrong Lisa :)
> add 'cache' line in travis.yml file

- app/assets/stylesheets/custom/_layout.scss
- app/views/layouts/application.html.erb
- app/views/pages/index.html.haml
https://github.com/simonwhitaker/github-fork-ribbon-css/
https://simonwhitaker.github.io/github-fork-ribbon-css/
cuz ppl are asking to contribute
related to https://github.com/rubycorns/rorganize.it#contributing
> fork me on github banner

- db/migrate/20150719091734_add_admin_to_people.rb
- db/seeds.rb
@til is this what you meant?
I dropped my local database & tried it out and it didn't complain, so that's good at least!
> Fix migration for postgres

- app/controllers/application_controller.rb
- app/controllers/people_controller.rb
- app/controllers/registrations_controller.rb
- app/views/devise/registrations/_form.html.haml
- app/views/people/_form.html.haml
- app/views/people/edit.html.haml
- app/views/people/show.html.haml
- spec/controllers/people_controller_spec.rb
- spec/features/edit_person_spec.rb
I was at the airport & refactored. 
* people are now updated in the person controller & not in the user registration controller
* forms are changed & split up to reflect this change
> make forms & controllers make sense for person

- app/views/coaches/index.html.haml
> Sr coach index deets

- app/models/person.rb
- spec/models/person_spec.rb
closes https://github.com/rubycorns/rorganize.it/issues/384
Now people can have one name, two, three, four, or even 100!
All names except for the last are considered to be first names. 
Suggestions welcome!
> account for multiple names & only one

- app/controllers/coaches_controller.rb
- app/controllers/groups_controller.rb
- app/models/person.rb
- app/views/coaches/index.html.haml
- app/views/groups/index.html.haml
- app/views/shared/_filter.html.haml
This touches on two issues #376 and #369
I feel like there is something missing, but please do take a look into it.... thoroughly!
Looking forward to the feedback :)
> Coach page filter and filter partial

- app/assets/stylesheets/custom/_people.scss
- app/controllers/coaches_controller.rb
- app/controllers/groups_controller.rb
- app/controllers/people_controller.rb
- app/models/group.rb
- app/models/person.rb
- app/views/coaches/index.html.haml
- app/views/people/index.html.haml
- app/views/shared/_filter.html.haml
- db/schema.rb
- spec/factories/people.rb
- spec/models/group_spec.rb
- spec/models/person_spec.rb
In this PR, I:
* refactored the shared filter a bit
* added the filter to the people index (so that you can filter people by city & country now as well)
* added the option to filter the coaches page by `willing_to_travel`
* added specs
lemmie know what you think!
> Willing to travel filter

- app/controllers/people_controller.rb
> Improve wording on profile updating notice

- app/views/dashboards/show.html.haml
just added some little guys here
> add some count information to the admin dashboard

- .travis.yml
> switch to docker infrastructure

- app/views/layouts/application.html.erb
- spec/features/not_logged_in_user_spec.rb
- spec/features/workshop_coach_spec.rb
> Adds dropdown to 'People' in navigation, see #375.

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/groups_map.js
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/custom/_groups_people.scss
- app/helpers/groups_helper.rb
- app/views/groups/show.html.haml
- app/views/layouts/application.html.erb
- config/initializers/leaflet.rb
This is just a start to our effort to move away from the leaflet rails gem. It doesn't ACTUALLY  solve the original problem of the scroll zoom, but I wanted to present it, to make sure I was heading in the right direction
> starts fix of #271

- app/models/concerns/location_filter.rb
- app/models/concerns/twitter_handle.rb
- app/models/group.rb
- app/models/person.rb
> refactor & remove empty strings from dropdown

- LICENSE
> add AGPL license

- app/controllers/dashboards_controller.rb
- app/controllers/posts_controller.rb
- app/helpers/posts_helper.rb
- app/models/post.rb
- app/views/posts/show.html.haml
- db/migrate/20160105185150_change_date_format_in_posts_table.rb
- db/schema.rb
- lib/tasks/blogpost_publish_dates.rake
- spec/controllers/posts_controller_spec.rb
- spec/factories/posts.rb
- spec/models/post_spec.rb
This is a new attempt at this forward and back button mess on the blog post show page.
We need to update the scope to not order things, but we are concerned that other things are dependant on it. It would be great to have a thorough look over this, and really check how deep the rabbit hole has gone. Who knew forward and back buttons were so complicated :)
> Sr pagination 232

- db/seeds.rb
With a fresh rails installation and a seeded database, when I try to edit a group as a coach and save without changes I get validation errors.
1. log in as coach
2. go to groups index
3. join group as a coach
4. edit group
5. click on update without changes
> fixed seeds.rb, missing normalization

- README.md
I got some errors when I tried to deploy, so this is mostly copy paste convenience
> Update deployment commands

- app/views/dashboards/show.html.haml
... instead of hacking the link_to helper
> use mailto helper

- app/controllers/groups_controller.rb
- app/views/groups/_form.html.haml
- app/views/groups/index.html.haml
- app/views/groups/show.html.haml
- db/migrate/20160327223742_add_male_students_flag_to_groups.rb
- db/schema.rb
- spec/features/group_edit_spec.rb
Hey there!
As we had the this discussion some time ago, I'll just did a simple implementation of an indicator if a group welcomes men as students.
Please let me now what you think.
I also added some explanations about our other flags.
> add male_student flag

- app/controllers/groups_controller.rb
- app/views/groups/_one_group.html.haml
- app/views/groups/index.html.haml
List active groups first, then inactive groups.
Does that make sense?
> Divide groups into active/inactive #index, close #436

- app/assets/stylesheets/redesign.css.scss
- app/views/layouts/application.html.erb
Adds params redesign for @katrin-k's design overhaul.
To see future changes in the desing add changes to `redesign.css.scss`, then add "?redesign=true" to url, e.g. "https://rorganize.it/coaches?redesign=true".
(Currently it just completely breaks the desing and colors the background purple. Because I like purlple.)
Closes #470.
> Params for redesign.

- app/controllers/application_controller.rb
- app/views/groups/index.html+redesign.haml
> Shows redesign html files on params "redesign"

- app/uploaders/picture_uploader.rb
Fixes the pixelation of the group thumb pics.
> Group thump picture bigger in order to not get pixely

- app/views/coaches/index.html+redesign.haml
- app/views/groups/_one_group.html+redesign.haml
- app/views/groups/index.html+redesign.haml
- app/views/layouts/application.html+redesign.erb
- app/views/pages/about.html+redesign.haml
- app/views/pages/index.html+redesign.haml
- app/views/people/index.html+redesign.haml
- app/views/posts/index.html+redesign.haml
- app/views/shared/_group_picture.html+redesign.haml
Adds redesign files for the HTML files that have been reworked so far in branch 468-redesign.
Belongs to issue #468.
> Create redesign variant files

- app/assets/stylesheets/redesign.css.scss
Here's the redesign CSS file, as mentioned in closed PR #476 // cc @til .
> Initial redesign CSS for merge into master

- app/assets/javascripts/main.js
If the URL contains the string "redesign", all links on the page will get the param `?redesign=true` added to their hrefs.
> Set redesign param for all links

- deploy/autostart
Has to get symlinked into service folder on uberspace.
Closes #480
> Adds deamon to autostart thin server if down

- scripts/uptime.sh
> add uptime script

- app/controllers/topics_controller.rb
- app/views/topics/index.html.haml
- spec/features/group_topics_spec.rb
but keep edit functionality excusive to group members
> make topics and comments visible to everyone, close #481

- app/assets/javascripts/redesign-main.js
- app/assets/stylesheets/redesign/_buttons.scss
- app/assets/stylesheets/redesign/_layout.scss
- app/assets/stylesheets/redesign/_profiles.scss
- app/views/coaches/index.html+redesign.haml
- app/views/devise/registrations/new.html+redesign.haml
- app/views/groups/_leave.html+redesign.haml
- app/views/groups/new.html+redesign.haml
- app/views/groups/show.html+redesign.haml
- app/views/layouts/application.html+redesign.erb
- app/views/people/show.html+redesign.haml
This Pull Request is the work in progress for the new redesign.
In an effort to deploy in stages, it would be great for everyone to look and make comments that you feel should be kept in mind for the first iteration
Please note that currently there is not a 'mobile' version of the site. To make sure it won't be too mammoth, it is wise to try and break the merges down. 
This PR has a number of improvements so take a look at things
- The map
- Twitter
- the things that each commit fixed
This will still lie behind the /?redesign param for now, so keep this in mind when reviewing; it's in process
> [WIP] Redesign

- db/seeds.rb
Until now, inside seeds, we create users and groups, but groups are empty. 
This PR aims to improve database seed info, by adding existing users to "The Rubycorns" group.
> Add members to group

- app/views/coaches/index.html+redesign.haml
@katrin-k I'm not sure if you already noticed/fixed this. if so, feel free to delete this PR. If not, feel free to merge (provided you're happy with this & it makes sense). 
Lemmie know if you have any questions/concerns.
> only highlight logged in user on coach page (fixes #498)

- app/controllers/groups_controller.rb
Closes #504 
@lislis & @til is this what you meant?
> refactor groups controller collections

- Gemfile
- Gemfile.lock
We removed a few other gems in the process.
> removes some unused gems

- app/assets/stylesheets/custom/_dashboard.scss
- app/assets/stylesheets/custom/_layout.scss
- app/assets/stylesheets/custom/_lists.scss
- app/assets/stylesheets/custom/_pages.scss
- app/assets/stylesheets/custom/_profiles.scss
- app/assets/stylesheets/custom/_resets.scss
- app/views/dashboards/_posts.html.haml
- app/views/shared/_groups.html.haml
- app/views/topics/_list_item.html.haml
- app/views/topics/index.html.haml
- app/views/topics/show.html.haml
- spec/features/group_topics_spec.rb
Related issue: #520 
Adds ul styles, minor style changes around lists
> Check ul styles to avoid markdown problems

- app/views/topics/show.html.haml
> Topics: fix back link vom view topic page

- app/views/topics/show.html.haml
Reverts rubycorns/rorganize.it#529
> Revert "Topics: fix back link vom view topic page"

- app/controllers/groups_controller.rb
- app/controllers/people_controller.rb
Hello, this is for #536. I've changed it so the filter options are displayed alphabetically for city and country.
I'm open to suggestions.
Regarding testing, is this something that would be worth writing a test for? Keen to hear your opinions on this.
> Order filter options alphabetically (City and Country)

- app/controllers/groups_controller.rb
- app/controllers/people_controller.rb
- app/helpers/groups_helper.rb
- app/models/group.rb
- app/models/person.rb
- app/views/groups/_form.html.haml
- app/views/groups/show.html.haml
- app/views/people/_form.html.haml
- app/views/people/show.html.haml
- app/views/shared/_grouped_people.haml
- db/migrate/20170214202206_searching_status.rb
- db/schema.rb
- spec/features/searching_status_spec.rb
- spec/fixtures/vcr_cassettes/create_group.yml
> Searching statuses for people and groups, closes #287

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/custom/_footer.scss
- app/views/layouts/application.html.erb
looks like this on ubuntu.
The 'icons' are unicode emoji so they might look different anywhere else :)
> add a footer, close #533

- app/assets/stylesheets/custom/_layout.scss
- app/assets/stylesheets/custom/_pages.scss
- app/views/layouts/application.html.erb
This PR will rejig a couple of elements on the home page just to improve the layout of some of the bigger items, and things that are currently overlapping and making it hard to navigate. WIP for now, but will remove the WIP when it is ready for proper review
> update responsive styles for home page

- app/models/person.rb
- spec/models/person_spec.rb
The aim is to improve name import from Github
This solution, as suggested by @lislis, is not perfect but I think slightly better than previous; assume the first name is the first name and all others are last name.
> Adresses #531 re importing profile names from Github.

- Gemfile
- Gemfile.lock
- app/assets/javascripts/main.js
- app/assets/stylesheets/custom/_layout.scss
- app/assets/stylesheets/custom/_lists.scss
- app/assets/stylesheets/custom/_profiles.scss
- app/views/dashboards/show.html.haml
- app/views/groups/show.html.haml
- db/schema.rb
- spec/features/people_non_public_profile_spec.rb
- spec/features/searching_status_spec.rb
- spec/features/workshop_coach_spec.rb
Issue #523  
Problem: The topics tab is not shown when there are no topics, but the user is member of a group and is allowed to start topics.
> Group profile: Tabbed content for resources, topics and members

- app/views/layouts/application.html.erb
Just fixing a minor minor thing. If you want to bundle any other typos, I can do it here... Otherwise, feel free to review and merge at will! pew pew!
> fixes typo in footer

- app/views/groups/show.html.haml
Move students list to proper place in the groups#show view.
> Move students list up to proper position under students list.

- app/assets/stylesheets/custom/_pages.scss
- app/views/pages/welcome.html.haml
> some welcome page styles

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/custom/_profiles.scss
- app/assets/stylesheets/custom/map.sass
- app/views/groups/show.html.haml
> adjust profile responsiveness

- app/assets/javascripts/application.js
- app/assets/javascripts/groupsMap.js
- app/assets/javascripts/indexMap.js
- app/assets/stylesheets/custom/_nav.scss
- app/assets/stylesheets/custom/map.sass
- app/views/pages/index.html.haml
- spec/features/not_logged_in_user_spec.rb
I added a global map of all groups to the landing page and changed the copy a bit.
> Landing update

- app/assets/stylesheets/custom/_layout.scss
- app/assets/stylesheets/custom/_nav.scss
- app/assets/stylesheets/custom/_pages.scss
- app/views/dashboards/show.html.haml
- app/views/groups/manage_members.html.haml
- app/views/posts/edit.html.haml
- app/views/posts/new.html.haml
make base font larger
make fonts landing page bigger
add padding container to more views
> Fix some issues that appeared with the last style update

- app/views/people/_form.html.haml
To manually update github handle as stated [here](https://github.com/rubycorns/rorganize.it/issues/602)
None
What happens when a user enters a github handle that is not theirs?
Profile page
> Add form field for GitHub handle

- app/controllers/pages_controller.rb
- app/views/pages/index.html.haml
Query Optimization in pages_controller and dashboards_controller
None
No
Index page
> Optimize index action of pages_controller

- app/views/groups/show.html.haml
I think I broke group tabs (topics and learning resources) and this PR fixes it.
n/a
n/a
n/a
> fix tabs on group#show

- app/controllers/people_controller.rb
- app/views/people/_form.html.haml
- spec/features/edit_person_spec.rb
- spec/features/group_sub_pages_spec.rb
#603
Not sure how the option to delete the image should work.
I check a checkbox that then calls a remove image method somewhere?
n/a
> display profile image in form if present and add option to remove it

- app/controllers/groups_controller.rb
- app/models/group.rb
Fixes this [issue](https://github.com/rubycorns/rorganize.it/issues/611)
> Refactor group controller

- app/helpers/application_helper.rb
- app/views/groups/index.html.haml
- spec/features/group_edit_spec.rb
- spec/features/groups_filter_spec.rb
- spec/fixtures/vcr_cassettes/create_group.yml
- spec/helpers/application_helper_spec.rb
#525
I started with the filter in groups#index.
People#index still needs to be done
If anyone has opinions on how to 'beautify' this, I'm all ears :D
n/a
> Indicate param filters

- app/views/people/index.html.haml
- spec/features/people_filter_spec.rb
> make person filter explicit

- app/assets/stylesheets/custom/_subnav.scss
- app/controllers/groups_controller.rb
- app/models/group.rb
- app/views/groups/_subnav.html.haml
- config/routes.rb
- spec/features/group_sub_pages_spec.rb
> Consolidate group nav

- app/assets/stylesheets/custom/_layout.scss
nope, I noticed while using the live site
n/a
n/a
Pages with only few elements in the main content. Previously the footer was jumping, now it should stay at the end of the page
> use flexbox to make footer sticky

- .gitignore
- Gemfile.lock
- config/initializers/geocoder.rb
- config/secrets.yml.sample
- spec/fixtures/vcr_cassettes/create_group.yml
- spec/support/vcr.rb
> Use mapbox for geocoder

- app/controllers/application_controller.rb
- app/controllers/posts_controller.rb
- spec/controllers/posts_controller_spec.rb
Yes, https://github.com/rubycorns/rorganize.it/issues/645
not that i can think of, but let me know
Is this a good way to do solve this problem?
You could run the query in the issue (with the SQL injection attempt) to see if you get a bad request error (instead of us getting an exception email)
> [645] add 500 error when trying to access nonexistent blog page

- spec/factories/groups.rb
- spec/factories/people.rb
- spec/factories/posts.rb
> fix rubocop deprecation warning, close #659

- README.md
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/custom/_profiles.scss
- app/assets/stylesheets/custom/_tags.scss
- app/controllers/groups_controller.rb
- app/controllers/invites_controller.rb
- app/controllers/people_controller.rb
- app/mailers/person_mailer.rb
- app/models/group.rb
- app/models/invite.rb
- app/models/person.rb
- app/views/groups/_join.html.haml
- app/views/groups/_subnav.html.haml
- app/views/groups/manage_members.html.haml
- app/views/people/_group_invites.html.haml
- app/views/people/_group_memberships.html.haml
- app/views/people/show.html.haml
- app/views/person_mailer/invitation_accepted.html.haml
- app/views/person_mailer/invitation_rejected.html.haml
- app/views/person_mailer/new_invitation.html.haml
- config/environments/development.rb
- config/routes.rb
- db/migrate/20180710170749_create_invites.rb
- db/schema.rb
- spec/controllers/invites_controller_spec.rb
- spec/controllers/memberships_controller_spec.rb
- spec/factories/invites.rb
- spec/features/group_member_spec.rb
- spec/fixtures/vcr_cassettes/create_group.yml
- spec/models/person_spec.rb
#449
This is one of the biggest changes yet and it will take me some time to work through this.
If you find any edge cases that should be tested, please tell me!
I'll introduce the concept of an invite. Invites are temporary relationships between a person and a group, similar to memberships but, well, temporary.
A user request membership to a group, an invite is **created**.
A group member either accepts or rejects it. Both actions **destory** the invite with the only difference being that accept also creates a membership.
So far the plan. I had some other ideas, that's why the model is a bit weird, not sure if I keep it or throw it out.
> Group invites, closes #449

- app/controllers/groups_controller.rb
- app/views/groups/_subnav.html.haml
- app/views/groups/my_groups.html.haml
- config/routes.rb
- spec/controllers/groups_controller_spec.rb
[664](https://github.com/rubycorns/rorganize.it/issues/664)
It adds `My Groups` to tab
Nil
The group's tab
> Add my groups tab

- app/controllers/groups_controller.rb
- app/views/groups/_subnav.html.haml
[667](https://github.com/rubycorns/rorganize.it/issues/667)
The group's tab
> Show my groups tab only when authenticated

- app/assets/javascripts/main.js
[647](https://github.com/rubycorns/rorganize.it/issues/647)
Nil
> Remove flash message from DOM

- app/assets/stylesheets/custom/_buttons.scss
- app/assets/stylesheets/custom/_profiles.scss
- app/models/null_person.rb
- app/views/groups/_delete.html.haml
- app/views/groups/show.html.haml
- spec/features/group_member_spec.rb
[650](https://github.com/rubycorns/rorganize.it/issues/650)
Visit a group page as a group admin
> Group admin can delete their group

- .travis.yml
Closes #665 
n/a
n/a
- did the build run successfully?
> remove sudo:false from travis.yml

- app/models/group.rb
No, it's a problem I experienced, getting the project up and running from scratch
Please do speak up if it's a weird thing to do. I'm open to suggestions, but it seemed like a decent solution to avoid any confusion for new users about why they can't seed data
Is there a better way?
Ensure that you can follow the readme instructions step by step and...
1) Create a group manually in the interface after dropping/creating/migrating the database from scratch
2) Run the `bundle exec rake db:seed` task on an empty/near empty database.
> Turn off geocoding in Development

- app/views/devise/confirmations/new.html.haml
- app/views/devise/passwords/edit.html.haml
- app/views/devise/passwords/new.html.haml
- app/views/devise/registrations/_form.html.haml
- app/views/devise/registrations/edit.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/devise/unlocks/new.html.haml
> Use render partials instead of deprecated devise_error_messages!
