.travis.yml
Dear Rubycorns,
I would like to have this mail removed because I am not using it anymore.
Thanks :cat: 
Lost Rubycorn Malwine
=> Remove non-used mail from Malwine

app/assets/javascripts/main.js, app/assets/stylesheets/custom/custom.css.scss, app/models/group.rb, app/views/groups/_form.html.haml, app/views/groups/new.html.haml, app/views/shared/_error_messages.html.haml, spec/controllers/groups_controller_spec.rb, spec/factories/groups.rb, spec/features/group_create_spec.rb
+ Group email = required
+ Contact info = required
+ Styles for flash messages updated to pink background and centered
+ All tests pass
We both fields necessary because email is for us (the app maintainers) whereas contact info is for people interested in the group.
Because most groups use googlegroups we didn't change contact info to email field.
=> Makes contact info and email required for groups.

Gemfile, Gemfile.lock, app/controllers/posts_controller.rb, app/helpers/posts_helper.rb, app/models/post.rb, app/views/posts/_post.html.haml, db/migrate/20150514115024_add_publication_date_to_post.rb, db/schema.rb, lib/tasks/blogpost_publish_dates.rake, spec/controllers/posts_controller_spec.rb, spec/factories/posts.rb, spec/models/post_spec.rb
I'm so lost at the moment. This is so solve the bug https://github.com/rubycorns/rorganize.it/issues/327. I decided not to use the `updated_at` column as the publication date, because what if someone updates an old post!? It's publication date would change! That would just be madness. So I created a new `publication_date` column for posts and am trying to use that.
In post#update, I'm trying to set a post's publication date if it was previously a draft, and is no longer. That's the `!@post.draft && @post.draft_changed?` part. 
Then the `@post.set_publication_date!` method is called, which should set the post's publication date. 
IT DOES. I can see it happening with all of my crazy ramblings in the code there where I look to see if it's been set. 
However, once the post is reloaded, it …
=> Add publication date to posts

app/controllers/dashboards_controller.rb, app/controllers/posts_controller.rb, app/models/post.rb, app/views/dashboards/_posts.html.haml, app/views/dashboards/show.html.haml, app/views/posts/index.html.haml, spec/controllers/posts_controller_spec.rb, spec/features/blog_draft_spec.rb, spec/models/post_spec.rb
Ummmmmm turns out I totally did all the backend for for using the `published_on date`, (see https://github.com/rubycorns/rorganize.it/pull/334) but I didn't actually USE it anywhere. This PR handles that.
=> actually USE published_on date

app/controllers/groups_controller.rb, app/models/group.rb, app/views/groups/_form.html.haml, app/views/groups/show.html.haml, db/migrate/20150614105629_add_learning_resources_to_groups.rb, db/schema.rb, spec/controllers/groups_controller_spec.rb, spec/factories/groups.rb, spec/features/group_create_spec.rb
This closes issue #339
Along the way, I also re-arranged the order of fields in the groups form. I think before we were just adding whatever new field to the end of the form, so things were a bit mixed up. I think it makes more sense now, but let me know if I'm way off base. 
I also added some text to clarify the difference between the email field and the contact field.
I also noticed that the form made it look as though city & country are required (they had *'s beside them). This however was not the case for realz. I added validations to these two fields & fixed the tests. Was there a reason why we were presenting them like they were required but weren't actually making them required?
I think once this is merged we should send an email to all groups asking them to update their …
=> Learning resources

app/controllers/people_controller.rb, app/views/coaches/index.html.haml, app/views/people/_form.html.haml, app/views/people/edit.html.haml, db/migrate/20150825174702_add_willing_to_travel_to_people.rb, db/migrate/20150825180539_add_city_to_people.rb, db/migrate/20150825181332_add_country_to_people.rb, db/schema.rb, spec/features/edit_person_spec.rb
This PR adds:
* willing to travel checkbox
* city field
* country field
to user. 
It also explains a bit about what the Rails Girls Coaches feature is, and what it means to click all these boxes. 
Adding city & country will help us/organizers filter the coaches better.
Til and I also discussed a bit what to do about email addresses: we decided not to display the email addresses of users, and instead if a Rails Girls organizer wants to USE our coach list, they have to contact us and prove that they are trustworthy, and then we will send the email addresses to them. I think this is cool for now and can totes be expanded upon in the future if need be.
=> get lots of info for coaches page

app/helpers/people_helper.rb, app/views/people/show.html.haml
@BriocheBerlin and @berlintam also worked on this. 
fixes #373
We just updated the people/show view to display if the person has opted to be a coach and if they have specified a location we will display that too.
=> adds coach location on profile page if it exists

app/assets/stylesheets/custom/_groups_people.scss, app/assets/stylesheets/custom/_people.scss, app/assets/stylesheets/custom/custom.css.scss, app/controllers/omniauth_callbacks_controller.rb, app/models/person.rb, app/views/layouts/application.html.erb, app/views/pages/about.html.haml, app/views/people/show.html.haml, spec/features/sign_in_spec.rb, spec/models/person_spec.rb
closes #382 like a boss. 
There's now a link on someone's profile page (if they're logged in and if they're not yet merged w/ github) offering a person an opportunity to link their rorganize account with their github account. 
If they click on this button, they will be able to login with github in da future. 
woot. Check it @PragTob :smile:
=> merge user & github accounts via profile

README.md, app/controllers/people_controller.rb, app/models/person.rb, app/views/people/_form.html.haml, app/views/people/show.html.haml, app/views/shared/_website.html.haml, db/migrate/20151006193254_add_website_to_people.rb, db/schema.rb, spec/features/edit_person_spec.rb
Enable adding website to profile as described in [#353](https://github.com/rubycorns/rorganize.it/issues/353) 
TODO:
Additionally:
- we adjusted the readme on how to run the specs
- we changed the label tag of the person/edit to be connected to the input in order to put the focus when clicking the label
=> (WIP) Enable adding website to profile

app/views/pages/about.html.haml, app/views/person_mailer/new_member_email.html.haml
closes #404 
Unfortunately I couldn't find the link in the email that still points to railgsirlsapp.shellycloud.com. Everything in the email seems fine unless I'm missing something....
=> remove railsgirlsapp

Gemfile.lock
I noticed that you [updated ```json``` and ```eventmachine```](https://github.com/rubycorns/rorganize.it/commit/bd536b15457994626bcf27b2c9423ed025f7b9be). I was wrong to believe that it is a problem for linux users, it seems to be a problem just for me. But if you want to make my life easier, well.. thanks :smiley_cat: 
Nevertheless, you probably want to update ```geocoder```. The current master branch spits out some [deprecation warnings](https://travis-ci.org/rubycorns/rorganize.it/jobs/102158129) if you run ```bundle exec rspec```.
=> update geocoder (deprecation warnings)

app/assets/stylesheets/custom/_groups_people.scss, app/views/coaches/index.html.haml, app/views/groups/index.html.haml, app/views/people/index.html.haml, app/views/shared/_filter.html.haml
This PR adds a reset button to the person & group forms (via the filter partial). Resetting in this case just means redirecting back to either the groups page or the people page. 
I'm a bit confused thou about why I had to do `locals[:path]` [here](https://github.com/rubycorns/rorganize.it/compare/add-reset-button?expand=1#diff-133e1f0b65a4cb828384db8ecd25dc41R22) instead of just `path` since I'm passing it through the locals. I thought that maybe it wasn't working because `path` is a reserved word, so I changed it to a bunch of other things trying to fix it, but it didn't work either. Any thoughts are very welcome!
=> add reset button to filter

Gemfile, Gemfile.lock, spec/controllers/groups_controller_spec.rb, spec/controllers/memberships_controller_spec.rb, spec/features/admin_remove_person_spec.rb, spec/features/group_create_spec.rb, spec/features/group_delete_spec.rb, spec/features/group_edit_spec.rb, spec/features/group_topics_spec.rb, spec/features/not_logged_in_user_spec.rb, spec/features/slug_spec.rb, spec/fixtures/vcr_cassettes/create_group.yml, spec/models/group_spec.rb, spec/models/membership_spec.rb, spec/models/person_spec.rb, spec/support/vcr.rb
fixes #361 
Whenever you ```create(:group)``` in the tests you trigger the geocode api in an [after_validation](https://github.com/rubycorns/rorganize.it/blob/master/app/models/group.rb#L50) hook. I decided to use an explicit cassette in every rspec context that uses this group factory. We could also do something similar to [*this*](http://stackoverflow.com/q/16533980). But it adds extra complexity and you get confused if you write another rspec test that triggers a different http request. In my opinion, the ideal solution would be to follow [this suggestion](http://stackoverflow.com/a/7861809).
=> Isolate tests from network connection

Gemfile
In development environment ```bin/rake db:setup``` fails because it's surpressing http requests.
=> Catch http requests only for test environment

app/helpers/application_helper.rb, app/helpers/groups_helper.rb, app/models/concerns/location_filter.rb, app/views/coaches/index.html.haml, app/views/people/show.html.haml, app/views/shared/_filter.html.haml, db/seeds.rb, spec/features/group_edit_spec.rb, spec/helpers/application_helper_spec.rb, spec/helpers/groups_helper_spec.rb, spec/models/concerns/location_filter_spec.rb
closes #419
I didn't only change them in the filter dropdown but also in various other places like the person#show and the people indexes etc.... so in THEORY, there shouldn't be any iso codes for countries anymore, it should all just be full country names.
=> display country name everywhere not iso_code

app/views/groups/index.html.haml
closes https://github.com/rubycorns/rorganize.it/issues/435
the badge is yellow.... I made a choice. `¯\_(ツ)_/¯`
=> inactive badge on index

app/helpers/groups_helper.rb, app/models/group.rb, app/views/groups/show.html.haml, spec/helpers/groups_helper_spec.rb, spec/models/group_spec.rb
closes https://github.com/rubycorns/rorganize.it/issues/434
It is also the end of an era.... bye bye `even_a_button?`. It's been a blast. But unfortunately, you make no sense anymore. 
What are you even doing? I no longer know.
=> remove signup buttons for inactive groups

app/controllers/groups_controller.rb
This fixes #465 (makes the reset button show up as well)
The error message when I tried recreating the bug locally was "undefined method `by_city' for #<Array:...>", so I assume it was caused by the following:
"partition" returns an array, and by_country/by_city are scopes which can only be called on ActiveRecord::Relation objects.
Please correct me if I am wrong :)
=> Fix bug filtering groups

README.md, deploy/autostart, deploy/restart
- Removes autostart file (now on server only)
- Changes restart file from restarting thin to killing thin
(so deamontools can restart server)
- Updates readme
- Hopefully closes #480
=> Autostarts thin server using deamontools

app/controllers/application_controller.rb, app/views/people/show.html+redesign.haml, spec/features/edit_person_spec.rb, spec/features/group_create_spec.rb, spec/features/group_edit_spec.rb, spec/features/update_password_spec.rb
[Add "change password" option #483](https://github.com/rubycorns/rorganize.it/issues/483)
This PR implements correct path for `Change password` button and makes change password works.
=> Add action for Change Password link 

app/views/devise/registrations/edit.html+redesign.haml, app/views/devise/registrations/edit.html.haml, app/views/devise/registrations/new.html.haml, app/views/devise/shared/_links.html.haml
Solves issue #483, regenerating the required view to change a user's password. 
(Note: The submit-button is currently not displayed correctly. Will be solved by the next PR for the redesign. Coming in 3…2… today…)
=> #483: Adjust views in app/view/devise/registrations to change password

app/views/devise/registrations/new.html.haml, spec/features/sign_up_spec.rb
looks like our current sign up behaviour is broken. A user is required to provide us with a first name when signing up, but our form only asks for an email & password. So try as you might, you can't sign up!
https://rorganize.it/people/sign_up
This fixes it. We also didn't have a spec for signing up, so it's understandable that this slipped through the cracks.
=> allow users to sign up again

app/controllers/coaches_controller.rb, app/controllers/groups_controller.rb, app/controllers/pages_controller.rb, app/controllers/people_controller.rb, app/models/person.rb, app/views/groups/show.html.haml, app/views/pages/index.html.haml, app/views/people/_form.html.haml, app/views/people/show.html.haml, config/autoprefixer.yml, db/migrate/20170127155731_add_non_public_flag_to_people.rb, db/schema.rb, db/seeds.rb, spec/features/people_non_public_profile_spec.rb, spec/spec_helper.rb
I added a 'private' flag to user profiles.
When your account is private your account is not visible at all for non-registered/ non-signed-in users.
This means that it does not show on the people overview page or the individual group pages.
Todo: add tests
=> Add private profiles, closing #284

app/assets/stylesheets/custom/_groups_people.scss, app/controllers/coaches_controller.rb, app/controllers/people_controller.rb, app/views/coaches/index.html.haml, app/views/people/index.html.haml, app/views/shared/_alphabetical_list.haml, app/views/shared/_grouped_people.haml
This is semi-resolving issue #370 
I added alphabetical jump links for the people and coaches index pages, exciting stuff! I also refactored a bit as there was a lot of repetition between the people#index and the coach#index. I pulled a bunch of it out into partials. 
I'm only working in the non-redesign area thou, as I don't want to touch the redesign stuff until it's up and running & for realz. But since this is mostly in partials, switching it over to the redesign when ready shouldn't be much of a problem. 
I have no specs, as it's mostly display stuff & I don't really want to write a feature spec for this. But maybe a little bit of a controller spec? Thoughts?
Anyway, here's a screenshot:
As always, review & comments always welcome!
=> add alphabetical jump links to people/coach index pages

app/assets/stylesheets/custom/_buttons.scss, app/assets/stylesheets/custom/_layout.scss, app/assets/stylesheets/custom/_lists.scss
Things this PR does
- Updates the stacking for smaller screens to column based flex layout, for lists like people and groups
- Ensures that the filter goes to the top of the list. 
Screenshots for demonstration
Please feel free to ask any questions, and thorough reviews are appreciated!!!
=> [513] adds media queries using variables

app/assets/stylesheets/custom/_buttons.scss, app/assets/stylesheets/custom/_profiles.scss, app/views/groups/show.html.haml
Just updating some of the layouts to help spread out the infos.
In this pull request I am going to update the group show page. Below are some screenshots to demonstrate what it looks like now and what the updates will do.
Current:
What this PR changes it to:
Note that these pictures look a bit big, but they are on a 500px screen, so imagine mobile. Feel free to pull the branch in and try it out yourself 
Many thanks in advance for the review liebe Rubycorns!!
=> update some of the group show page layout

app/controllers/groups_controller.rb, app/models/group.rb
This Addresses Issue #535.
In The Group Model, I've Added A `before_save` Method To Capitalize A City's Name Before Saving To The Database.
=> Capitalizing City Name Before Save - in progress

Gemfile.lock, app/assets/stylesheets/custom/_layout.scss
fixes #557 
Short and sweet addition, as the logo was jumping up to take 60% of the page, and not its container. 
Probably good to have a set height on the logo, so thought this was a good solution
=> fixes 557 with px units

app/views/devise/registrations/_form.html.haml, spec/features/sign_up_spec.rb
Signup form in `registrations#new` view should initially focus the first input field, not the third one
=> Fix signup form to autofocus first input field

spec/spec_helper.rb, spec/support/vcr.rb
This disables http connections when running specs to ensure tests are run against the fixtures, not the live apis. Our tests shouldn't depend on the reachability of the apis to work. 
Verified that it works by disabling wifi. Tests in master fail with 'could not connect to geocoding api', tests in this branch work.
=> Don't allow http connections during specs

app/assets/stylesheets/custom/_lists.scss, app/views/people/index.html.haml, app/views/shared/_grouped_people.haml
retry for https://github.com/rubycorns/rorganize.it/pull/512
slight problem is, if we have an alphabetical list (from A-Z) and go to /people, we display the people whose names start with Z first, not the ppl whose names start with A. 
@sareg0 is gonna take another look at this! suggestions welcome on how to get the page to display at A group first :)
(ex: in the screenshot you can see that if you go to /people the last alphabetical group of people is shown first)
=> display alphabetical group when clicked (pagination)

app/assets/stylesheets/custom/_nav.scss
This PR fixes the navigation item been too close. A design bug 
#593 
The PR fixes the design issue in the navigation item been too close by tweaking the css responsible
None
- Visit the website and check out the main navigation. You will notice more spaces between the main navigation item.
**The current state**
**The desired state based on my implementation**
=> fix main nav item too close bug

.rubocop.yml, Gemfile, Gemfile.lock, spec/controllers/admin_controller_spec.rb, spec/controllers/groups_controller_spec.rb, spec/controllers/memberships_controller_spec.rb, spec/controllers/people_controller_spec.rb, spec/controllers/posts_controller_spec.rb, spec/controllers/registrations_controller_spec.rb, spec/spec_helper.rb
It removes all devise deprecation warnings as specified [here](https://github.com/rubycorns/rorganize.it/issues/621)
Rubocop was added as a form of linter, more rules can be added later.
none
The tests by running `rspec`
=> Remove devise deprecation warnings

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/custom/_buttons.scss, app/assets/stylesheets/custom/_layout.scss, app/assets/stylesheets/custom/_lists.scss, app/assets/stylesheets/custom/_nav.scss, app/assets/stylesheets/custom/_person.sass, app/assets/stylesheets/custom/_profiles.scss, app/assets/stylesheets/custom/_util.sass, app/controllers/coaches_controller.rb, app/controllers/people_controller.rb, app/helpers/people_helper.rb, app/views/coaches/index.html.haml, app/views/groups/_meeting_info.haml, app/views/groups/_one_group.html.haml, app/views/groups/show.html.haml, app/views/layouts/application.html.erb, app/views/people/_profile_edit_actions.haml, app/views/people/_subnav.haml, app/views/people/index.html.haml, app/views/people/show.html.haml, app/views/shared/_group_picture.html.haml, app/views/shared/_person_picture.html.haml, spec/features/workshop_coach_spec.rb
#597 
Here is a pic with the new arrangement of all things that can be in the profile
=> Rearrange person profile

config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
"Luke warm" fix for a current production issue. 
Error: 
```
RuntimeError: Couldn't find Active Storage configuration in /home/ror/rorganize.it/config/storage.yml
```
solution taken from: https://stackoverflow.com/questions/49813214/disable-active-storage-in-rails-5-2
=> Disable active storage
